title: eBook Store
email: valchevgd@gmail.com
description: Find Your Favorite Book
destination: docs
#baseurl: "/eBookStore"
baseurl: ""
url: ""
github_username:  valchevgd
exclude: [_assets, node_modules, gulpfile.js, Gemfile, Gemfile.lock, package.json, package-lock.json]
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
